<?php

namespace Database\Seeders;

use App\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Przykładowe produkty – odzież używana.
     */
    public function run(): void
    {
        $baseUrl = rtrim(config('app.url'), '/');

        $products = [
            [
                'name' => 'Bawełniana koszulka oversize',
                'description' => 'Luźna, przewiewna koszulka z bawełny. Idealna na lato. Po jednym noszeniu, bez śladów zużycia.',
                'price' => 49.99,
                'sale_price' => 39.99,
                'category' => 'odziez',
                'size' => 'M',
                'condition' => 'excellent',
                'brand' => 'H&M',
                'color' => 'biały',
                'images' => [$baseUrl.'/images/products/koszulka.svg'],
                'stock_quantity' => 5,
                'sku' => 'SKU-10001',
            ],
            [
                'name' => 'Koszulka z nadrukiem vintage',
                'description' => 'Koszulka band z lat 90. Oryginalny nadruk, lekko wyblakły. Unikalny charakter.',
                'price' => 89.00,
                'sale_price' => null,
                'category' => 'odziez',
                'size' => 'L',
                'condition' => 'good',
                'brand' => 'Vintage',
                'color' => 'czarny',
                'images' => [$baseUrl.'/images/products/koszulka.svg'],
                'stock_quantity' => 2,
                'sku' => 'SKU-10002',
            ],
            [
                'name' => 'Bluza z kapturem',
                'description' => 'Ciepła bluza z kapturem. Wewnątrz wyłożona miękkim materiałem. Idealna na jesień.',
                'price' => 79.99,
                'sale_price' => 59.99,
                'category' => 'odziez',
                'size' => 'S',
                'condition' => 'excellent',
                'brand' => 'Nike',
                'color' => 'szary',
                'images' => [$baseUrl.'/images/products/bluza.svg'],
                'stock_quantity' => 4,
                'sku' => 'SKU-10003',
            ],
            [
                'name' => 'Bluza oversize na zamek',
                'description' => 'Bardzo luźna bluza zapinana na zamek. Wygodna, casualowy styl.',
                'price' => 95.00,
                'sale_price' => null,
                'category' => 'odziez',
                'size' => 'XL',
                'condition' => 'good',
                'brand' => 'Adidas',
                'color' => 'granatowy',
                'images' => [$baseUrl.'/images/products/bluza.svg'],
                'stock_quantity' => 3,
                'sku' => 'SKU-10004',
            ],
            [
                'name' => 'Spodnie jeansowe slim fit',
                'description' => 'Klasyczne spodnie jeansowe w dopasowanym kroju. Świetnie się noszą.',
                'price' => 69.99,
                'sale_price' => 54.99,
                'category' => 'odziez',
                'size' => 'M',
                'condition' => 'excellent',
                'brand' => 'Levi\'s',
                'color' => 'niebieski',
                'images' => [$baseUrl.'/images/products/spodnie.svg'],
                'stock_quantity' => 6,
                'sku' => 'SKU-10005',
            ],
            [
                'name' => 'Spodnie chino',
                'description' => 'Eleganckie spodnie chino. Idealne do pracy i na co dzień.',
                'price' => 59.00,
                'sale_price' => null,
                'category' => 'odziez',
                'size' => 'L',
                'condition' => 'good',
                'brand' => 'Zara',
                'color' => 'beżowy',
                'images' => [$baseUrl.'/images/products/spodnie.svg'],
                'stock_quantity' => 4,
                'sku' => 'SKU-10006',
            ],
            [
                'name' => 'Sukienka letnia',
                'description' => 'Lekka sukienka na lato. Kwiatowy wzór, krótki rękaw. Stan idealny.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'category' => 'odziez',
                'size' => 'S',
                'condition' => 'excellent',
                'brand' => 'Reserved',
                'color' => 'wielokolorowy',
                'images' => [$baseUrl.'/images/products/sukienka.svg'],
                'stock_quantity' => 3,
                'sku' => 'SKU-10007',
            ],
            [
                'name' => 'Sukienka elegancka',
                'description' => 'Elegancka sukienka na specjalne okazje. Dopasowany krój, wyściółka.',
                'price' => 149.00,
                'sale_price' => null,
                'category' => 'odziez',
                'size' => 'M',
                'condition' => 'excellent',
                'brand' => 'Mango',
                'color' => 'czarny',
                'images' => [$baseUrl.'/images/products/sukienka.svg'],
                'stock_quantity' => 2,
                'sku' => 'SKU-10008',
            ],
            [
                'name' => 'Kurtka zimowa',
                'description' => 'Ciepła kurtka zimowa z wypełnieniem. Ocieplana, wodoodporna.',
                'price' => 199.99,
                'sale_price' => 159.99,
                'category' => 'odziez',
                'size' => 'L',
                'condition' => 'good',
                'brand' => 'North Face',
                'color' => 'zielony',
                'images' => [$baseUrl.'/images/products/kurtka.svg'],
                'stock_quantity' => 2,
                'sku' => 'SKU-10009',
            ],
            [
                'name' => 'Kurtka jeansowa',
                'description' => 'Klasyczna kurtka denim. Uniwersalna, pasuje do wszystkiego.',
                'price' => 79.00,
                'sale_price' => null,
                'category' => 'odziez',
                'size' => 'M',
                'condition' => 'good',
                'brand' => 'Lee',
                'color' => 'niebieski',
                'images' => [$baseUrl.'/images/products/kurtka.svg'],
                'stock_quantity' => 4,
                'sku' => 'SKU-10010',
            ],
            [
                'name' => 'Trampki sportowe',
                'description' => 'Wygodne trampki do codziennego użytku. Czyste, bez przetarć.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'category' => 'obutrze',
                'size' => '42',
                'condition' => 'excellent',
                'brand' => 'Converse',
                'color' => 'biały',
                'images' => [$baseUrl.'/images/products/obuwie.svg'],
                'stock_quantity' => 3,
                'sku' => 'SKU-10011',
            ],
            [
                'name' => 'Buty casualowe',
                'description' => 'Wygodne buty na co dzień. Skórzany wierzch, gumowa podeszwa.',
                'price' => 120.00,
                'sale_price' => null,
                'category' => 'obutrze',
                'size' => '43',
                'condition' => 'good',
                'brand' => 'Clarks',
                'color' => 'brązowy',
                'images' => [$baseUrl.'/images/products/obuwie.svg'],
                'stock_quantity' => 2,
                'sku' => 'SKU-10012',
            ],
            [
                'name' => 'Torba podróżna',
                'description' => 'Duża torba na ramię. Wiele kieszeni, wytrzymały materiał.',
                'price' => 59.99,
                'sale_price' => 49.99,
                'category' => 'akcesoria',
                'size' => null,
                'condition' => 'excellent',
                'brand' => 'unknown',
                'color' => 'czarny',
                'images' => [$baseUrl.'/images/products/torba.svg'],
                'stock_quantity' => 5,
                'sku' => 'SKU-10013',
            ],
            [
                'name' => 'Szal wełniany',
                'description' => 'Miękki szal z wełny. Idealny na chłodniejsze dni.',
                'price' => 45.00,
                'sale_price' => null,
                'category' => 'akcesoria',
                'size' => null,
                'condition' => 'excellent',
                'brand' => null,
                'color' => 'burgund',
                'images' => [$baseUrl.'/images/products/szal.svg'],
                'stock_quantity' => 7,
                'sku' => 'SKU-10014',
            ],
            [
                'name' => 'Czapka z daszkiem',
                'description' => 'Sportowa czapka z daszkiem. Oryginalny nadruk.',
                'price' => 35.00,
                'sale_price' => 29.99,
                'category' => 'akcesoria',
                'size' => 'uni',
                'condition' => 'good',
                'brand' => 'Puma',
                'color' => 'niebieski',
                'images' => [$baseUrl.'/images/products/koszulka.svg'],
                'stock_quantity' => 6,
                'sku' => 'SKU-10015',
            ],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(
                ['sku' => $data['sku']],
                array_merge($data, ['reserved_quantity' => 0])
            );
        }
    }
}
